mod 'autoconf', '0.0.1', :github_tarball => 'boxen/puppet-autoconf'
mod 'libtool',  '0.0.1', :github_tarball => 'boxen/puppet-libtool'
mod 'xquartz',  '0.0.1', :github_tarball => 'boxen/puppet-xquartz'
